# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeimdallmCli < Formula
  desc "CLI client for Heimdallm — monitor PRs, issues, and activity from the terminal"
  homepage "https://github.com/theburrowhub/heimdallm"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.6.3/heimdallm-cli_0.6.3_darwin_amd64.tar.gz"
      sha256 "f1a30172c8728dd6c833476119b92f9552c447d1a65d4d49edf50596cdfab66b"

      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.6.3/heimdallm-cli_0.6.3_darwin_arm64.tar.gz"
      sha256 "45f8b0845919b9d85b82274cc3df15702bc0f87d8ae66261b1ab7036aca59497"

      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.6.3/heimdallm-cli_0.6.3_linux_amd64.tar.gz"
      sha256 "7da1ad5dacb56bec4fcbf189c199fd8a6ca37a5fca7393a047bff049b163b41e"
      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.6.3/heimdallm-cli_0.6.3_linux_arm64.tar.gz"
      sha256 "2dca13b6a900ec22ce6ac2940b4bd25486ef460ab236ba6b920c1c74572a6265"
      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
  end

  test do
    system "#{bin}/heimdallm-cli", "--help"
  end
end
