# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeimdallmCli < Formula
  desc "CLI client for Heimdallm — monitor PRs, issues, and activity from the terminal"
  homepage "https://github.com/theburrowhub/heimdallm"
  version "0.8.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.8.27/heimdallm-cli_0.8.27_darwin_amd64.tar.gz"
      sha256 "d6760b25453dc9c7c96d5e78f3efc981bbd8816f2180887bbdd05ca755728837"

      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.8.27/heimdallm-cli_0.8.27_darwin_arm64.tar.gz"
      sha256 "79b5a4f2c7e187b5709be0ed7d188c031fd0622cbf271ddaadf4df44ba6bd561"

      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.8.27/heimdallm-cli_0.8.27_linux_amd64.tar.gz"
      sha256 "3f5b94be332c07079d8e81440ef350d368e8ed300297974ba56a6ba9dc24a69f"
      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/heimdallm/releases/download/v0.8.27/heimdallm-cli_0.8.27_linux_arm64.tar.gz"
      sha256 "4f6fad5efea96e197e0ace60e3e75a2e213e01bfb3ead2c3b20fc20a3f5e3109"
      define_method(:install) do
        bin.install "heimdallm-cli"
      end
    end
  end

  test do
    system "#{bin}/heimdallm-cli", "--help"
  end
end
