# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krakenv < Formula
  desc "Environment variable management tool with annotation-based wizards"
  homepage "https://github.com/theburrowhub/krakenv"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.7/krakenv_0.0.7_darwin_amd64.tar.gz"
      sha256 "39b591f6a7317eb7d44680301daf26ff8142e7dd97705b8dc86ebb9c517d5718"

      define_method(:install) do
        bin.install "krakenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.7/krakenv_0.0.7_darwin_arm64.tar.gz"
      sha256 "8a42aa07752ab1a5d8f4cd6229382a0b076e3163a8eeb93fcad905bb6d3ae72b"

      define_method(:install) do
        bin.install "krakenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.7/krakenv_0.0.7_linux_amd64.tar.gz"
      sha256 "8580d9bc40e8b50a5f742035346fc9bfd0ca084632e27e94c0d9d9ae7a0deebc"
      define_method(:install) do
        bin.install "krakenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.7/krakenv_0.0.7_linux_arm64.tar.gz"
      sha256 "3987e1d8be89604ae762e2503bbbe75bdd386d39a7d70f6aa96f1f82d27b5e1d"
      define_method(:install) do
        bin.install "krakenv"
      end
    end
  end

  test do
    system "#{bin}/krakenv", "version"
  end
end
