# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krakenv < Formula
  desc "Environment variable management tool with annotation-based wizards"
  homepage "https://github.com/theburrowhub/krakenv"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.6/krakenv_0.0.6_darwin_amd64.tar.gz"
      sha256 "4ae89d905dc2e74b113806b84498ee1f549bb3b6857da4f6bb3e7de7e46faa3d"

      def install
        bin.install "krakenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.6/krakenv_0.0.6_darwin_arm64.tar.gz"
      sha256 "35d6926459f4df6c89bbb96a777d85f5aa661be9d6ff05b26d4c7a9128e63c6b"

      def install
        bin.install "krakenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.6/krakenv_0.0.6_linux_amd64.tar.gz"
      sha256 "0bb5f6f09eab1d532a89c1f1722f8d9416957f688b7445aeb55c6d2adb7ca3ff"
      def install
        bin.install "krakenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/theburrowhub/krakenv/releases/download/v0.0.6/krakenv_0.0.6_linux_arm64.tar.gz"
      sha256 "44f0e0df6293f4ca8286d057a3be6b204b2aa724d0c1b6b893699a438bb4b146"
      def install
        bin.install "krakenv"
      end
    end
  end

  test do
    system "#{bin}/krakenv", "version"
  end
end
